# Generated by Django 4.0.6 on 2022-09-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(default='', max_length=30)),
                ('moodnum', models.IntegerField(default=0)),
                ('journal', models.CharField(blank=True, max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMood', to='APP.user')),
            ],
        ),
    ]
