# Generated by Django 4.0.6 on 2022-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_groupmembership_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
