# Generated by Django 4.0.6 on 2022-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='diet',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='image',
            name='exercise',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='image',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
    ]
